Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using MedicalAppointmentDotNet.Models;
using MedicalAppointmentDotNet.Persistance;
using Microsoft.AspNetCore.Mvc;

namespace MedicalAppointmentDotNet.Controllers
{
    public class DoctorController : Controller
    {
        
        public IActionResult Index()
        {
            List<Doctor> doctors = w.Load();
            return View(doctors);
        }
        public IActionResult CreateDoctor() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateDoctor(Doctor doctor) 
        {
            List<Doctor> doctors = DoctorPersistance.Load();
            doctors.Add(
                new Doctor(
                    doctor.FirstName,
                    doctor.LastName,
                    doctor.Address,
                    doctor.PhoneNumber,
                    doctor.Birthdate,
                    doctor.Specialty
                )
            );
            DoctorPersistance.Save(doctors);
            return Redirect("Index");
        }
    }
}

Controllers/EmployeeController.cs
using MedicalAppointmentDotNet.Models;
using MedicalAppointmentDotNet.Persistance;
using Microsoft.AspNetCore.Mvc;

namespace MedicalAppointmentDotNet.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Index()
        {
            var employees = EmployeePersistance.Load();
            return View(employees);
        }
        public IActionResult CreateEmployee()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateEmployee(Employee employee)
        {
            var employees = EmployeePersistance.Load();
            employees.Add(new Employee(
                employee.FirstName,
                employee.LastName,
                employee.Address,
                employee.PhoneNumber,
                employee.Birthdate
            ));
            EmployeePersistance.Save(employees);
            return Redirect("Index");
        }
    }
}

Controllers/MedicalAppointmentController.cs
using MedicalAppointmentDotNet.Models;
using MedicalAppointmentDotNet.Persistance;
using Microsoft.AspNetCore.Mvc;

namespace MedicalAppointmentDotNet.Controllers
{
    public class MedicalAppointmentController : Controller
    {
        public IActionResult Index() 
        {
            var medicalAppointments = MedicalAppointmentPersistance.Load();
            return View(medicalAppointments);
        }
        public IActionResult CreateMedicalAppointment()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateMedicalAppointment(MedicalAppointment medicalAppointment)
        {
            var medicalAppointments = MedicalAppointmentPersistance.Load();
            medicalAppointments.Add(
                new MedicalAppointment(
                    medicalAppointment.Date,
                    medicalAppointment.DoctorId,
                    medicalAppointment.PatientId
                )
            );
            MedicalAppointmentPersistance.Save(medicalAppointments);
            return Redirect("Index");
        }
    }
}

Controllers/PatientController.cs
using MedicalAppointmentDotNet.Models;
using MedicalAppointmentDotNet.Persistance;
using Microsoft.AspNetCore.Mvc;

namespace MedicalAppointmentDotNet.Controllers
{
    public class PatientController : Controller
    {
        public IActionResult Index()
        {
            var patients = PatientPersistance.Load();
            return View(patients);
        }
        public IActionResult CreatePatient()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreatePatient(Patient patient)
        {
            var patients = PatientPersistance.Load();
            patients.Add(new Patient(
                patient.FirstName,
                patient.LastName,
                patient.Address,
                patient.PhoneNumber,
                patient.Birthdate
            ));
            PatientPersistance.Save(patients);
            return Redirect("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MedicalAppointmentDotNet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MedicalAppointmentDotNet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Doctor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="CreateDoctor">Create Doctor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="CreateEmployee">Create Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="Index">Patient</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="CreatePatient">Create Patient</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MedicalAppointment" asp-action="Index">Medical Appointments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MedicalAppointment" asp-action="CreateMedicalAppointment">Create Medical Appointment</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MedicalAppointmentDotNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>